INSERT INTO minibadge.badge_type(label, picture_id, description)
VALUES
    ('Animation', 'animation.svg', 'Tu aimes gérer l’animation d’un groupe, tu fais ce qu’il faut pour que chacun participe et se sente intégré aux activités.'),
    ('Sens artistique', 'artistique.svg', 'Tu t''es investi dans la création ou dans une pratique artistique (musique, dessin, danse, cinéma, etc.) et tu partages ta passion'),
    ('AS Numérique', 'as-numerique.svg', 'Tu es très à l''aise avec les outils numériques et tu aimes toujours apprendre à utiliser de nouveaux outils'),
    ('Bien être animal', 'bien-etre-animal.svg', 'Tu adores les animaux mais surtout tu sais expliquer les conditions que l’homme doit mettre en place pour assurer à l’animal son bien-être.'),
    ('Bienveillance', 'bienveillance.svg', 'Quand on te parle de nos problèmes, tu nous écoutes attentivement. Tu as toujours une attitude positive envers les autres.'),
    ('Bravo', 'bravo.svg', 'Tu es vivement félicité pour ce que tu as réussi'),
    ('Citoyenneté', 'citoyennete.svg', 'Tu est intéressé par les sujets politiques, de civisme et d''engagement citoyen'),
    ('Couteau suisse', 'couteau-suisse.svg', 'Tu as toujours beaucoup d''idées originales, des solutions techniques ou pratiques pour débloquer une situation. Tu sais faire beaucoup de choses car tu aimes bricoler !'),
    ('Ecologie', 'ecologie.svg', 'Tu es passionné par les questions de sciences naturelles, d''environnement et de climat et tu aimes partager ton savoir.'),
    ('Egalité genre', 'egalite-genre.svg', 'Tu luttes selon tes moyens contre les discriminations liées au genre. Tu t’impliques pour sensibiliser les autres.'),
    ('Environnement', 'environnement.svg', 'Tu veilles aux respect des méthodes de tris et de recyclage. Tu t''impliques pour aider aux économies d''énergie.'),
    ('Implication', 'implication.svg', 'Fort investissement dans les activités et projets de la classe, de l''école ou de l''établissement'),
    ('Maitre lettres', 'maitre-lettres.svg', 'Tu adores la lecture, l''art du récit et la culture en général'),
    ('Médiation', 'mediation.svg', 'Tu facilites la résolution de conflits'),
    ('Merci', 'merci.svg', 'Tu as rendu un très grand service'),
    ('Motivation', 'motivation.svg', 'Rien ne peut t’arrêter !'),
    ('Ouverture esprit', 'ouverture-esprit.svg', 'Tu fais des efforts pour comprendre les autres même quand tu n’es pas d’accord'),
    ('Patience', 'patience.svg', 'Tu ne t’énerves jamais, même quand c’est difficile'),
    ('Responsable', 'responsable.svg', 'Tu tiens tes promesses. Tu mènes à bien les projets qu''on te confie et tu prends tes responsabilités'),
    ('Savoir être', 'savoir-etre.svg', 'Toujours attentif et respectueux des autres.'),
    ('Savoir vivre', 'savoir-vivre.svg', 'Respecter les lieux et le matériel, ranger et laisser propre est très important pour toi.'),
    ('Aime les sciences', 'sciences.svg', 'Tu aimes expliquer les matières scientifiques'),
    ('Sentinelle', 'sentinelle.svg', 'Tu es attentif aux problèmes de harcèlement, notamment sur les réseaux sociaux'),
    ('Solidaire', 'solidaire.svg', 'Tu ne laisses pas les autres dans la difficulté sans réagir. Tu fais toujours de ton mieux pour les soutenir.'),
    ('Sourire', 'sourire.svg', 'Tu as toujours le sourire et ton attitude est communicative.'),
    ('Totalement sport', 'sport.svg', 'Le sport fait partie de ton quotidien, tu es impliqué au sein d''une association ou tu es incollable sur une pratique sportive en particulier.'),
    ('Travail équipe', 'travail-equipe.svg', 'Tu travailles toujours au service du collectif'),
    ('Tutorat', 'tutorat.svg', 'Le tutorat entre pairs repose sur la possibilité, pour un élève plus compétent (le tuteur), d’expliquer comment faire à un autre (le tutoré) qui, tout seul, ne parviendrait pas à réaliser correctement une tâche. Il ne s’agit pas simplement de diriger l’action de l’individu aidé, ni de faire à sa place, mais de le soutenir dans la construction de sa propre démarche pour qu’il devienne capable de faire par lui-même Liens : <a href="https://urldefense.com/v3/__https://www4.ac-nancy-metz.fr/pasi/IMG/9MalrauxRemiremontNM.pdf__;!!AaIhyw!rrjitXbu-baf4ycSK3wQGF-VPYIOjZgfJvaXHgpxxsmOjPD_kgRaWP0SKb9J_2ZA4q1LK4naV4gwqCxG1Zp7eK7RH9w9iDiU-PaB$">Plus d''info</a>');