UPDATE minibadge.badge_type AS bt
SET description_short = updates.description_short,
    description       = updates.description FROM (VALUES
        ('BIEN_ETRE_ANIMAL',
        '<p>Tu respectes les animaux, tu connais leurs besoins et tu sais expliquer les conditions que l’homme doit mettre en place pour assurer leur bien-être.</p>',
        '<p>Il est important de tenir compte du bien-être animal car cela nous permet de diminuer la souffrance des animaux et de contribuer à la santé et à la diversité de notre monde. En tenant compte de leur bien-être, nous pouvons changer nos façons d''intéragir avec eux pour leur témoigner du respect et leur donner de bonnes conditions de vie. Les animaux font partie de notre écosystème et jouent un rôle important dans notre environnement. S’attacher au bien-être animal peut être une expérience enrichissante et gratifiante. Cela peut nous aider à découvrir de nouvelles choses et à nous sentir utiles en faisant quelque chose de positif pour les animaux.</p><p>Le badge « Bien-être animal » fait partie des mini-badges qui sont des signes de reconnaissance au format numérique (une image et une explication). Ils permettent de montrer sur l’ENT ce que l’on sait faire ou ce qu’on a appris, et les personnes qui nous reconnaissent pour cela. Le mini-badge peut être proposé à des camarades avec qui on travaille et à qui on souhaite reconnaître une qualité, une aptitude, un talent, ou tout simplement pour les remercier pour quelque chose qu’ils nous ont apporté.</p><p>Pour en savoir plus sur les badges, rendez-vous sur le site <a href="https://reconnaitre.openrecognition.org/mini-badges/">Reconnaitre - Open Recognition</a></p>'),
        ('ECOLOGIE',
        '<p>Tu es passionné par les questions de sciences naturelles, d''environnement et de climat et tu aimes échanger et discuter sur ces sujets.</p>',
        '<p>Il est important de partager nos idées et nos connaissances sur les questions d''écologie car cela peut nous aider à prendre soin de notre environnement, à sensibiliser les gens aux problèmes environnementaux et à créer un monde plus durable pour tous. Nous vivons tous sur la même planète et nous sommes tous responsables de prendre soin de notre environnement. En partageant ce que nous savons sur l''écologie, nous pouvons aider les autres à comprendre comment protéger la nature et l''environnement, et à prendre des décisions écologiquement responsables. En apprenant de nouvelles choses sur l''écologie, nous pouvons mieux comprendre comment notre mode de vie a un impact sur la planète. Cela nous permet de prendre des décisions plus écologiques dans notre vie quotidienne, comme économiser l''eau et l''énergie, réduire nos déchets et choisir des produits écologiques.</p><p>Le badge « Écologie » fait partie des mini-badges qui sont des signes de reconnaissance au format numérique (une image et une explication). Ils permettent de montrer sur l’ENT ce que l’on sait faire ou ce qu’on a appris, et les personnes qui nous reconnaissent pour cela. Le mini-badge peut être proposé à des camarades avec qui on travaille et à qui on souhaite reconnaître une qualité, une aptitude, un talent, ou tout simplement pour les remercier pour quelque chose qu’ils nous ont apporté.</p><p>Pour en savoir plus sur les badges, rendez-vous sur le site <a href="https://reconnaitre.openrecognition.org/mini-badges/">Reconnaitre - Open Recognition</a></p>'),
        ('ENVIRONNEMENT',
        '<p>Tu t''impliques pour aider aux économies d''énergie. Tu veilles au respect des méthodes de tri et de recyclage.</p>',
        '<p>Il est important de s''impliquer dans la protection de l''environnement car cela nous permet de prendre soin de notre planète, de préserver la nature et de créer un avenir durable pour tous. Nous vivons tous sur la même planète et nous avons tous le devoir de prendre soin de notre environnement. En nous impliquant dans la protection de l''environnement, nous pouvons contribuer à préserver la nature et à assurer un avenir durable pour les générations à venir. L''environnement joue un rôle important dans notre vie quotidienne. Nous avons besoin de l''air, de l''eau et de la nourriture que la nature nous fournit. En prenant soin de notre environnement, nous pouvons assurer la qualité de ces ressources essentielles. L''environnement est menacé par de nombreux problèmes, tels que la pollution, la déforestation et le changement climatique. En nous impliquant dans la protection de l''environnement, nous pouvons aider à réduire ces problèmes.</p><p>Le badge « Environnement » fait partie des mini-badges qui sont des signes de reconnaissance au format numérique (une image et une explication). Ils permettent de montrer sur l’ENT ce que l’on sait faire ou ce qu’on a appris, et les personnes qui nous reconnaissent pour cela. Le mini-badge peut être proposé à des camarades avec qui on travaille et à qui on souhaite reconnaître une qualité, une aptitude, un talent, ou tout simplement pour les remercier pour quelque chose qu’ils nous ont apporté.</p><p>Pour en savoir plus sur les badges, rendez-vous sur le site <a href="https://reconnaitre.openrecognition.org/mini-badges/">Reconnaitre - Open Recognition</a></p>')
        ) as updates(slug, description_short, description)
where updates.slug = bt.slug;
