GRANT USAGE ON SCHEMA minibadge TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA minibadge TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA minibadge TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA minibadge TO "apps";

ALTER DEFAULT PRIVILEGES IN SCHEMA minibadge
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO "apps";

ALTER DEFAULT PRIVILEGES IN SCHEMA minibadge
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "apps";

ALTER DEFAULT PRIVILEGES IN SCHEMA minibadge
GRANT EXECUTE ON FUNCTIONS TO "apps";